### ISSUE TITLE
issues with regressor statement

### ISSUE THREAD

**Issue by alexisakov** [cran/dsa#1]
I'm trying to run dsa  for electricity consumption with regression on deviations of temperature fro the norm:

res <- dsa(xtsee, cval=7, automodel='reduced', Log = 1, regressor = xtstv)

xtsee is an xts object and ranges between 2007-01-01 and 2020-04-11
regressor xtstv also is an xts object and spans the same period between 2007-01-01 and 2020-04-11

However, running this code  gives me the following error:

Error in error(x, ...) :  improper length of one or more arguments to merge.xts

Could you advise on the proper use of the regressor option - may be the range is not correct? should I use the forecast_regressor option?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
